export type { Brand } from "./brand";

export type { CampaignId, CommandId, CheckpointId, PlayerId, WizardId, AllocationId, EngagementId, DenizenId, IsleId, PlaceId, CompanionRelationshipId, TreasureId, CampaignPowerfulDenizenTaxonomyId, PowerfulDenizenMethodEntryId, PowerfulDenizenTruthId, LoreCollectionId, LoreEntryId } from "./ids";
export {
  isValidCampaignId,
  parseCampaignId,
  isValidLiveCommandId,
  parseLiveCommandId,
  isValidCheckpointId,
  parseCheckpointId,
  isValidPlayerId,
  parsePlayerId,
  isValidWizardId,
  parseWizardId,
  isValidAllocationId,
  parseAllocationId,
  generateAllocationId,
  isValidEngagementId,
  parseEngagementId,
  generateEngagementId,
  isValidDenizenId,
  parseDenizenId,
  isValidIsleId,
  parseIsleId,
  isValidPlaceId,
  parsePlaceId,
  isValidCompanionRelationshipId,
  parseCompanionRelationshipId,
  isValidTreasureId,
  parseTreasureId,
  isValidCampaignPowerfulDenizenTaxonomyId,
  parseCampaignPowerfulDenizenTaxonomyId,
  isValidPowerfulDenizenMethodEntryId,
  parsePowerfulDenizenMethodEntryId,
  isValidPowerfulDenizenTruthId,
  parsePowerfulDenizenTruthId,
  generateLoreCollectionId,
  isValidLoreCollectionId,
  parseLoreCollectionId,
  generateLoreEntryId,
  isValidLoreEntryId,
  parseLoreEntryId,
} from "./ids";

export type {
  MonthOrdinal,
  MonthId,
  MonthDirection,
  MonthDisplayName,
  MonthOfYearIndex,
  SeasonId,
} from "./calendar";
export {
  MONTH_IDS,
  MONTH_DISPLAY_NAMES,
  MONTH_COUNT,
  INITIAL_MONTH_ORDINAL,
  monthOfYearIndexFromOrdinal,
  monthIdFromOrdinal,
  displayNameFromMonthId,
  displayNameFromOrdinal,
  seasonIdFromOrdinal,
  advanceOrdinal,
} from "./calendar";

export type { CampaignCommandType } from "./commands";
export {
  CAMPAIGN_COMMAND_TYPES,
  isLogicalStateCommandType,
  isHistoryNavigationCommandType,
} from "./commands";

export type {
  UndoAppliedDataV1,
  UndoAppliedEventV1,
  RedoAppliedDataV1,
  RedoAppliedEventV1,
  CheckpointRestoredDataV1,
  CheckpointRestoredEventV1,
  BackupImportedDataV1,
  BackupImportedEventV1,
  PlayerAddedEventV1,
  PlayerRenamedEventV1,
  PlayerRemovedEventV1,
  CampaignAgeChangedEventV1,
  FacilitatorAssignmentChangedEventV1,
  WizardCreatedEventV1,
  WizardNameChangedEventV1,
  WizardPortrayalChangedEventV1,
  PactSeatWizardChangedEventV1,
  PactSeatStatusChangedEventV1,
  WatcherAssignmentChangedEventV1,
  SetupMonthChangedEventV1,
  SetupOrreryPositionChangedEventV1,
  BeginPlayDataV1,
  BeginPlayEventV1,
  PhaseAdvancedEventV1,
  PhaseAdvancedEventV2,
  TimeAllocationScheduledEventV1,
  EngagementTargetChangedEventV1,
  WizardmootAttendanceAdjustedEventV1,
  MeetingCompletedEventV1,
  MonthBegunEventV1,
  WizardCharacterUpdatedEventV1,
  WizardCharacterUpdatedEventV2,
  EngagementTargetChangedEventV2,
  EngagementRescheduledEventV1,
  EngagementRescheduledEventV2,
  InfrastructureEvent,
  PhaseAdvancedEvent,
  WorldEvent,
  SharedStateEvent,
  DenizenCreatedDataV1,
  DenizenCreatedEventV1,
  DenizenUpdatedDataV1,
  DenizenUpdatedEventV1,
  IsleCreatedDataV1,
  IsleCreatedEventV1,
  IsleUpdatedDataV1,
  IsleUpdatedEventV1,
  PlaceCreatedDataV1,
  PlaceCreatedEventV1,
  PlaceUpdatedDataV1,
  PlaceUpdatedEventV1,
  WizardHomeIsleChangedDataV1,
  WizardHomeIsleChangedEventV1,
  WizardSanctumChangedDataV1,
  WizardSanctumChangedEventV1,
  WizardCompanionChangedDataV1,
  WizardCompanionChangedEventV1,
  CompanionDescriptionChangedDataV1,
  CompanionDescriptionChangedEventV1,
  HierophantInitializedDataV1,
  HierophantInitializedEventV1,
  TempleResourcesAdjustedDataV1,
  TempleResourcesAdjustedEventV1,
  HierophantEvent,
  MarinerEvent,
  MarinerInitializedDataV1,
  MarinerInitializedEventV1,
  MarinerShipChangedEventV1,
  MarinerSeaLawsChangedEventV1,
  MarinerRouteOccupancyChangedEventV1,
  MarinerSeaStormCountChangedEventV1,
  MarinerIsleMarketChangedEventV1,
  MarinerIsleRavageChangedEventV1,
  MarinerBeastAddedEventV1,
  MarinerBeastUpdatedEventV1,
  MarinerBeastRemovedEventV1,
  NecromancerEvent,
  NecromancerInitializedDataV1,
  NecromancerInitializedEventV1,
  NecromancerDepthChangedEventV1,
  NecromancerLawsChangedEventV1,
  NecromancerGateStatusChangedEventV1,
  NecromancerSoulCountChangedEventV1,
  NecromancerSoulsMovedEventV1,
  NecromancerFoeAddedEventV1,
  NecromancerFoeUpdatedEventV1,
  NecromancerFoeRemovedEventV1,
  NecromancerAllyAddedEventV1,
  NecromancerAllyUpdatedEventV1,
  NecromancerAllyRemovedEventV1,
  NecromancerGhoulCallerAddedEventV1,
  NecromancerGhoulCallerUpdatedEventV1,
  NecromancerGhoulCallerRemovedEventV1,
  NecromancerCampaignGateCreatedEventV1,
  NecromancerCampaignGateUpdatedEventV1,
  NecromancerCampaignPathSpaceCreatedEventV1,
  NecromancerCampaignPathSpaceRemovedEventV1,
  NecromancerStepAddedEventV1,
  NecromancerStepRemovedEventV1,
  FaustianEvent,
  FaustianCommunityInvestigatedDataV1,
  FaustianCommunityInvestigatedEventV1,
  FaustianCommunityBlackmailedDataV1,
  FaustianCommunityBlackmailedEventV1,
  FaustianAccompliceDirectedDataV1,
  FaustianAccompliceDirectedEventV1,
  FaustianPawnDisruptedDataV1,
  FaustianPawnDisruptedEventV1,
  SorcererInitializedDataV1,
  SorcererInitializedEventV1,
  SorcererEvent,
  LoreEntryAddedCollectionContextV1,
  LoreEntryAddedDataV1,
  LoreEntryAddedEventV1,
  LoreEntryRevisedTargetContextV1,
  LoreEntryRevisedDataV1,
  LoreEntryRevisedEventV1,
  LoreEvent,
  CampaignEvent,
} from "./events";

export type { RulesetRef } from "./ruleset";
export {
  SEVEN_PART_PACT_DRAFT4_ID,
  SEVEN_PART_PACT_DRAFT4_VERSION,
  CURRENT_RULESET,
} from "./ruleset";

export type {
  CampaignRevision,
  CampaignRuleset,
  CampaignStateV1,
  CampaignStateV2,
  CampaignStateV3,
  CampaignStateV4,
  CampaignStateV5,
  CampaignPlayer,
  LegacyCampaignWizard,
  CampaignWizardV4,
  CampaignWizard,
  CampaignWizardV5,
  WizardElementScores,
  WizardCompanionDescriptions,
  WizardCharacterDataV4,
  WizardCharacterData,
  WizardCharacterDataV5,
  PactSeatState,
  PactSeatStatus,
  LunarPhase,
  MonthlyPlayStateV4,
  MonthlyPlayState,
  MonthlyPlayStateV5,
  PlayLifecycleV4,
  PlayLifecycleV5,
  SetupLifecycle,
  PlayLifecycle,
  CampaignLifecycleV4,
  CampaignLifecycleV5,
  CampaignLifecycle,
  CurrentCampaignState,
  AnyCampaignState,
  PactFragmentCondition,
  PactFragmentCustody,
  PactFragmentOperationalState,
  PactFragmentOperationalMap,
} from "./campaign-state";
export {
  CURRENT_STATE_SCHEMA_VERSION,
  LUNAR_PHASES,
  BLANK_WIZARD_CHARACTER,
  BLANK_WIZARD_CHARACTER_V4,
  BLANK_WIZARD_CHARACTER_V5,
  PACT_FRAGMENT_CONDITIONS,
  EMPTY_PACT_FRAGMENT_OPERATIONAL_STATE,
  initializePactFragmentOperationalState,
} from "./campaign-state";

export type { WizardCharacterPatch } from "./wizard-character";
export { normalizeWizardCharacterPatch, applyWizardCharacterPatch } from "./wizard-character";

export type { PactSeatId } from "./pact-seats";
export { PACT_SEAT_IDS, PACT_SEAT_COUNT, pactSeatDisplayName, isValidPactSeatId } from "./pact-seats";

export type { AgeDefinitionId } from "./ages";
export { AGE_DEFINITION_IDS, ageDisplayName, isValidAgeDefinitionId } from "./ages";

export { migrateToCurrentVersion, loadHistoricalState, isHistoricalStateLogicallyEqual, isSupportedSchemaVersion, SUPPORTED_STATE_SCHEMA_VERSIONS } from "./state-migration";

export type { DomainErrorCode } from "./errors";
export { DomainError } from "./errors";

export { validateCampaignState, validateAnyCampaignState, validateCampaignStateV4Candidate, validateCampaignStateV5Candidate } from "./state-validation";

export { initialCampaignState } from "./initial-state";

export type { TransitionResult } from "./m3-transitions";
export {
  applyAddPlayer,
  applyRenamePlayer,
  applyRemovePlayer,
  applySetCampaignAge,
  applySetFacilitator,
  applyCreateWizard,
  applyRenameWizard,
  applySetWizardPortrayal,
  applySetPactSeatWizard,
  applySetPactSeatStatus,
  applySetWatcher,
  applySetSetupMonth,
  applySetSetupOrreryPosition,
  applyUpdateWizardCharacter,
} from "./m3-transitions";

export type {
  UndoTransitionInput,
  RedoTransitionInput,
  HistoryNavigationResult,
  UndoCoherenceInput,
  RedoCoherenceInput,
} from "./undo-redo";
export {
  deriveUndoTransition,
  deriveRedoTransition,
  validateUndoTransactionCoherence,
  validateRedoTransactionCoherence,
} from "./undo-redo";

export type { IdempotencyMatchResult } from "./command-ids";
export {
  syntheticMigrationCommandId,
  isSyntheticMigrationCommandId,
  migrationCommandFingerprint,
  undoFingerprint,
  redoFingerprint,
  checkpointRestoreFingerprint,
  backupImportFingerprint,
  addPlayerFingerprint,
  renamePlayerFingerprint,
  removePlayerFingerprint,
  setCampaignAgeFingerprint,
  setFacilitatorFingerprint,
  createWizardFingerprint,
  renameWizardFingerprint,
  setWizardPortrayalFingerprint,
  setPactSeatWizardFingerprint,
  setPactSeatStatusFingerprint,
  setWatcherFingerprint,
  setSetupMonthFingerprint,
  setSetupOrreryPositionFingerprint,
  updateWizardCharacterFingerprint,
  beginPlayFingerprint,
  advancePhaseFingerprint,
  normalizeWarningKeys,
  scheduleTimeFingerprint,
  setEngagementTargetFingerprint,
  rescheduleTimeFingerprint,
  spendManualTimeFingerprint,
  wasteTimeFingerprint,
  spendOrreryTimeFingerprint,
  commitTimeToEngagementFingerprint,
  resolveEngagementFingerprint,
  rescheduleEngagementFingerprint,
  adjustWizardmootAttendanceFingerprint,
  completeMeetingFingerprint,
  beginNextMonthFingerprint,
  createDenizenFingerprint,
  updateDenizenFingerprint,
  createIsleFingerprint,
  updateIsleFingerprint,
  createPlaceFingerprint,
  updatePlaceFingerprint,
  setWizardHomeIsleFingerprint,
  setWizardSanctumFingerprint,
  setWizardCompanionFingerprint,
  updateCompanionDescriptionFingerprint,
  initializeHierophantFingerprint,
  adjustTempleResourcesFingerprint,
  createTempleFingerprint,
  updateTempleFingerprint,
  setTempleHolidayFingerprint,
  setSelectedFlameLawsFingerprint,
  addSupplicantFingerprint,
  updateSupplicantFingerprint,
  removeSupplicantFingerprint,
  addProphetFingerprint,
  updateProphetFingerprint,
  removeProphetFingerprint,
  establishCultFingerprint,
  updateCultFingerprint,
  removeCultFingerprint,
  addCultDogmaFingerprint,
  updateCultDogmaFingerprint,
  removeCultDogmaFingerprint,
  createCampaignClassFingerprint,
  updateCampaignClassFingerprint,
  createCampaignDoctrineFingerprint,
  updateCampaignDoctrineFingerprint,
  initializeMarinerFingerprint,
  setMarinerShipFingerprint,
  setSelectedSeaLawsFingerprint,
  setMarinerRouteOccupancyFingerprint,
  setMarinerSeaStormCountFingerprint,
  setMarinerIsleMarketFingerprint,
  setMarinerIsleRavageFingerprint,
  addMarinerBeastFingerprint,
  updateMarinerBeastFingerprint,
  removeMarinerBeastFingerprint,
  initializeNecromancerFingerprint,
  setNecromancerDepthFingerprint,
  setSelectedDeathLawsFingerprint,
  setNecromancerGateStatusFingerprint,
  setNecromancerSoulCountFingerprint,
  moveNecromancerSoulsFingerprint,
  addNecromancerFoeFingerprint,
  updateNecromancerFoeFingerprint,
  removeNecromancerFoeFingerprint,
  escapeNecromancerWizardFoeFingerprint,
  addNecromancerWizardFoeTruthFingerprint,
  updateNecromancerWizardFoeTruthFingerprint,
  removeNecromancerWizardFoeTruthFingerprint,
  addNecromancerWizardTraversalFingerprint,
  updateNecromancerWizardTraversalFingerprint,
  removeNecromancerWizardTraversalFingerprint,
  addNecromancerAllyFingerprint,
  updateNecromancerAllyFingerprint,
  removeNecromancerAllyFingerprint,
  addNecromancerGhoulCallerFingerprint,
  updateNecromancerGhoulCallerFingerprint,
  removeNecromancerGhoulCallerFingerprint,
  createNecromancerCampaignGateFingerprint,
  updateNecromancerCampaignGateFingerprint,
  createNecromancerCampaignPathSpaceFingerprint,
  removeNecromancerCampaignPathSpaceFingerprint,
  addNecromancerStepFingerprint,
  removeNecromancerStepFingerprint,
  setWizardMortalityStateFingerprint,
  setDenizenMortalityStateFingerprint,
  createPowerfulDenizenProfileFingerprint,
  removePowerfulDenizenProfileFingerprint,
  setPowerfulDenizenTaxonomiesFingerprint,
  setPowerfulDenizenStatusFingerprint,
  setPowerfulDenizenGoalFingerprint,
  addPowerfulDenizenMethodFingerprint,
  updatePowerfulDenizenMethodFingerprint,
  removePowerfulDenizenMethodFingerprint,
  addPowerfulDenizenTruthFingerprint,
  updatePowerfulDenizenTruthFingerprint,
  removePowerfulDenizenTruthFingerprint,
  createCampaignPowerfulDenizenTaxonomyFingerprint,
  updateCampaignPowerfulDenizenTaxonomyFingerprint,
  removeCampaignPowerfulDenizenTaxonomyFingerprint,
  createTreasureFingerprint,
  updateTreasureDetailsFingerprint,
  updateTreasureStateFingerprint,
  updatePactFragmentOperationalStateFingerprint,
  investigateFaustianCommunityFingerprint,
  blackmailFaustianCommunityFingerprint,
  directFaustianAccompliceFingerprint,
  disruptFaustianPawnFingerprint,
  initializeSorcererFingerprint,
  addLoreEntryFingerprint,
  reviseLoreEntryFingerprint,
  matchCommandIdempotency,
  normalizeCheckpointLabel,
  validateCheckpointLabel,
} from "./command-ids";

export type {
  RevisionRecord,
  EventRecord,
  SnapshotRecord,
  VerificationResult,
  CampaignDocument,
  MigrationVerificationInput,
  SerializableCampaignState,
} from "./verification";
export {
  verifyMigrationInvariants,
} from "./verification";

export type { ActivityEntry } from "./activity";
export {
  mapEventToActivityEntry,
  describeActivityEntry,
} from "./activity";

export type {
  CampaignHistoryControlV1,
  HistoryControlValidationInput,
  RevisionCommandInfo,
  ReplayEventInfo,
  HistoryReplayInput,
  HistoryReplayResult,
  HistoryControlVerificationInput,
  InitializationRevisionInfo,
  InitializationEventInfo,
  InitializationSnapshotInfo,
  HistoryControlInitInput,
  HistoryControlInitResult,
} from "./history-control";
export {
  CURRENT_HISTORY_CONTROL_VERSION,
  validateHistoryControlStructure,
  replayHistoryControl,
  verifyHistoryControl,
  analyzeHistoryControlInitialization,
} from "./history-control";

export { statesDeepEqual, assertPortableCampaignState } from "./state-equality";
export type { PersistableCampaignState } from "./state-equality";

export type {
  CampaignCheckpointV1,
  CheckpointVerificationInput,
  CheckpointCollectionVerificationInput,
  RestoreRevisionVerificationInput,
} from "./checkpoints";
export {
  CURRENT_CHECKPOINT_VERSION,
  verifyCheckpoint,
  verifyCheckpointCollection,
  verifyCheckpointRestoreRevision,
} from "./checkpoints";

export type {
  CampaignBackupV1,
  CampaignBackupProvenanceV1,
  CampaignBackupIntegrityV1,
  BackupIntegrityPayload,
  BackupValidationError,
  ValidatedBackupV1,
  IntegrityVerifiedBackupV1,
  ExportSourceData,
} from "./backup";
export {
  BACKUP_FORMAT_TYPE,
  CURRENT_BACKUP_FORMAT_VERSION,
  MAX_PORTABLE_BACKUP_BYTES,
  buildIntegrityPayload,
  buildIntegrityPayloadFromParts,
  computeBackupPayloadDigest,
  parseAndValidateBackupStructure,
  validateBackupState,
  validateBackupCompatibility,
  fullyValidateBackup,
  parseAndVerifyBackupIntegrityForFingerprint,
  buildExportBackup,
} from "./backup";

export {
  canonicalJsonStringify,
  sha256Hex,
  computeDigestFromCanonicalJson,
  CanonicalJsonError,
} from "./canonical-json";

export type {
  DeletionPhase,
  DeletionOperation,
  CampaignOwnedChildCollection,
} from "./campaign-deletion";
export {
  DELETION_BATCH_SIZE,
  DELETION_CONFIRMATION_STRING,
  DELETION_PHASE_ORDER,
  CAMPAIGN_OWNED_CHILD_COLLECTIONS,
  validateDeletionRequest,
  validateCampaignIdentityMatch,
  assertNotDeleting,
  nextDeletionPhase,
  isDeletionChildCleanupPhase,
} from "./campaign-deletion";

export type { BackupImportRevisionVerificationInput } from "./backup-verification";
export {
  verifyBackupImportRevisionStructure,
  verifyBackupImportRevisionDigest,
} from "./backup-verification";

export type {
  DeletionPersistenceAdapter,
  RequestDeletionResult,
  BatchResult,
  LifecycleStatus,
} from "./deletion-orchestrator";
export {
  requestDeletion,
  processBatch,
  resolveLifecycle,
} from "./deletion-orchestrator";

// --- Orrery ---

export type {
  CentidegreePosition,
  MovablePlanetId,
  CelestialBodyId,
  HouseIndex,
  PlanetDefinition,
  SetupOrreryState,
  OrreryState,
  OrreryMoveDirection,
  BodyHouseOccupancy,
  Conjunction,
} from "./orrery";
export {
  FULL_CIRCLE_CENTIDEGREES,
  HOUSE_COUNT,
  HOUSE_WIDTH_CENTIDEGREES,
  MOVABLE_PLANET_IDS,
  CELESTIAL_BODY_IDS,
  HOUSE_NAMES,
  PLANET_DEFINITIONS,
  isValidCentidegreePosition,
  asCentidegreePosition,
  houseIndexFromCentidegrees,
  sunPositionFromMonthOrdinal,
  arcStartAndEnd,
  housesOccupiedByArc,
  housesOccupiedByBody,
  sunHouse,
  computeAllOccupancies,
  computeConjunctions,
  advancePlanetPosition,
  movePlanetByArc,
  legalPositionsForPlanet,
  isLegalPosition,
  isCompleteOrrery,
  emptySetupOrrery,
  advanceAllPlanets,
} from "./orrery";

// --- Participants ---

export type { WizardParticipantRef, DevilParticipantRef, TimeParticipantRef } from "./participants";
export { isWizardParticipantRef, isDevilParticipantRef, wizardIdOfParticipant } from "./participants";

// --- Time Model ---

export type {
  AllocationResolution,
  CompanionDestination,
  MapIsleSanctumDestination,
  FamiliarDestination,
  OrreryDestination,
  MeetingDestination,
  DomainDestination,
  EngagementDestination,
  SpecialUseDestination,
  TimeDestinationV4,
  TimeDestinationKindV4,
  DevilCommunityDestination,
  DevilSchemesDestination,
  DevilCompanionDestination,
  DevilGrimoireDestination,
  DevilWizardDestination,
  DevilDenizenDestination,
  DevilSeizedDomainDestination,
  DevilOnlyTimeDestination,
  DevilTimeDestination,
  DevilOnlyTimeDestinationKind,
  TimeDestinationV5,
  TimeDestinationKindV5,
  TimeDestination,
  TimeDestinationKind,
  TimeAllocationV4,
  TimeAllocationV5,
  TimeAllocation,
  TimeParticipantV4,
  TimeParticipantV5,
  TimeParticipant,
} from "./time-model";
export {
  ALLOCATION_RESOLUTIONS,
  TIME_DESTINATION_KINDS_V4,
  DEVIL_ONLY_TIME_DESTINATION_KINDS,
  TIME_DESTINATION_KINDS_V5,
  TIME_DESTINATION_KINDS,
  isDevilOnlyTimeDestination,
  isWizardTimeDestination,
  isDevilTimeDestination,
} from "./time-model";

// --- Engagement ---

export type {
  EngagementResolution,
  WizardTarget,
  SelfTarget,
  FamiliarTarget,
  NamedCharacterTarget,
  DenizenTarget,
  EngagementTargetV4,
  EngagementTarget,
  EngagementTargetV5,
  EngagementTargetKind,
  EngagementTargetKindV4,
  EngagementTargetKindV5,
  EngagementRecordV4,
  EngagementRecord,
  EngagementRecordV5,
} from "./engagement";
export { ENGAGEMENT_RESOLUTIONS, ENGAGEMENT_TARGET_KINDS, ENGAGEMENT_TARGET_KINDS_V4, ENGAGEMENT_TARGET_KINDS_V5 } from "./engagement";

// --- Wizardmoot ---

export type {
  WizardmootAttendance,
  WizardmootHistoryEntry,
} from "./wizardmoot";

// --- Setup Readiness ---

export type {
  SetupReadinessIssueCode,
  SetupReadinessIssue,
  SetupReadinessResult,
} from "./setup-readiness";
export { evaluateSetupReadiness } from "./setup-readiness";

// --- Age Setup ---

export type {
  AgeSetupIssueCode,
  AgeSetupIssue,
  AgeSetupResult,
} from "./age-setup";
export { evaluateAgeSetup } from "./age-setup";

// --- Begin Play ---

export type {
  WizardInitIds, BeginPlayInput,
} from "./begin-play";
export { applyBeginPlay, collectEligibleWizardIds, buildTimeParticipant, buildEngagement } from "./begin-play";

// --- Play Transitions (C3/C4/C5A) ---

export type { AdvancePhaseInput, AdvancePhaseResult, PhaseTransitionWarning, ScheduleTimeInput, SetEngagementTargetInput, RescheduleTimeInput, SpendManualTimeInput, WasteTimeInput, SpendOrreryTimeInput, CommitTimeToEngagementInput, ResolveEngagementInput, RescheduleEngagementInput, AdjustWizardmootAttendanceInput, CompleteMeetingInput, BeginNextMonthInput, BeginNextMonthResult } from "./play-transitions";
export {
  applyAdvancePhase,
  applyScheduleTime,
  applySetEngagementTarget,
  applyRescheduleTime,
  applySpendManualTime,
  applyWasteTime,
  applySpendOrreryTime,
  applyCommitTimeToEngagement,
  applyResolveEngagement,
  applyRescheduleEngagement,
  applyAdjustWizardmootAttendance,
  applyCompleteMeeting,
  applyBeginNextMonth,
  computePhaseTransitionWarnings,
} from "./play-transitions";

// --- Shared World (V5 candidate) ---

export type {
  ElementId,
  MortalityState,
  WizardOrDenizenSubjectRef,
  Denizen,
  Isle,
  UnspecifiedPlacement,
  OnIslePlacement,
  MobilePlacement,
  WorldPlacePlacement,
  WorldPlace,
  CompanionRelationshipStatus,
  CompanionRelationship,
  TreasureCondition,
  TreasureCustody,
  Treasure,
  SharedWorldState,
} from "./shared-world";
export { ELEMENT_IDS, MORTALITY_STATES, TREASURE_CONDITIONS, EMPTY_SHARED_WORLD_STATE } from "./shared-world";

export type {
  BuiltinPowerfulDenizenTaxonomyId,
  PowerfulDenizenBuiltinTaxonomyDefinition,
  PowerfulDenizenTaxonomyRef,
  CampaignPowerfulDenizenTaxonomy,
  PowerfulDenizenStandardStatus,
  PowerfulDenizenStatus,
  StandardPowerfulDenizenMethod,
  PowerfulDenizenMethodDefinition,
  PowerfulDenizenEntryOrigin,
  PowerfulDenizenMethodEntry,
  PowerfulDenizenTruthEntry,
  PowerfulDenizenProfile,
} from "./powerful-denizen";
export {
  POWERFUL_DENIZEN_BUILTIN_TAXONOMY_IDS,
  POWERFUL_DENIZEN_BUILTIN_TAXONOMY_DEFINITIONS,
  POWERFUL_DENIZEN_STANDARD_STATUS_VALUES,
  STANDARD_POWERFUL_DENIZEN_METHODS,
  isValidBuiltinPowerfulDenizenTaxonomyId,
  isValidPowerfulDenizenStandardStatus,
  isValidStandardPowerfulDenizenMethod,
  powerfulDenizenTaxonomyRefKey,
} from "./powerful-denizen";
export {
  denizenHasBuiltinTaxonomy,
  isReliableOrDisruptiveStatus,
  profileHasStandardRampagingMethod,
  requirePowerfulRoleProfile,
  requireReliableOrDisruptiveStatus,
  requireDisruptiveStatus,
  requireRampagingBeastMethod,
  powerfulStatusLabel,
} from "./powerful-denizen-roles";

// --- V5 Reference Validation (candidate, not active) ---

export { validateV5WorldReferenceIntegrity } from "./v5-reference-validation";

// --- V5 World Subject Transitions (candidate, not active) ---

export type {
  ExpectedFieldChange,
  DenizenTransitionResult,
  IsleTransitionResult,
  PlaceTransitionResult,
  WorldSubjectTransitionResult,
  CandidateWorldSubjectEvent,
  CreateDenizenInput,
  UpdateDenizenFields,
  CreateIsleInput,
  UpdateIsleFields,
  CreatePlaceInput,
  UpdatePlaceFields,
} from "./world-subject-transitions";
export {
  applyCreateDenizenV5Candidate,
  applyUpdateDenizenV5Candidate,
  applyCreateIsleV5Candidate,
  applyUpdateIsleV5Candidate,
  applyCreatePlaceV5Candidate,
  applyUpdatePlaceV5Candidate,
} from "./world-subject-transitions";

export type {
  SharedStateTransitionResult,
  CreatePowerfulDenizenProfileInput,
  AddPowerfulDenizenMethodInput,
  AddPowerfulDenizenTruthInput,
  CreateCampaignPowerfulDenizenTaxonomyInput,
  UpdateCampaignPowerfulDenizenTaxonomyFields,
  CreateTreasureInput,
  UpdateTreasureDetailsFields,
} from "./shared-state-transitions";
export {
  applySetWizardMortalityState,
  applySetDenizenMortalityState,
  applyCreatePowerfulDenizenProfile,
  applyRemovePowerfulDenizenProfile,
  applySetPowerfulDenizenTaxonomies,
  applySetPowerfulDenizenStatus,
  applySetPowerfulDenizenGoal,
  applyAddPowerfulDenizenMethod,
  applyUpdatePowerfulDenizenMethod,
  applyRemovePowerfulDenizenMethod,
  applyAddPowerfulDenizenTruth,
  applyUpdatePowerfulDenizenTruth,
  applyRemovePowerfulDenizenTruth,
  applyCreateCampaignPowerfulDenizenTaxonomy,
  applyUpdateCampaignPowerfulDenizenTaxonomy,
  applyRemoveCampaignPowerfulDenizenTaxonomy,
  applyCreateTreasure,
  applyUpdateTreasureDetails,
  applyUpdateTreasureState,
  applyUpdatePactFragmentOperationalState,
} from "./shared-state-transitions";

// --- V5 World Relationship Transitions (candidate, not active) ---

export type {
  RelationshipTransitionResult,
  WizardAssociationTransitionResult,
  CompanionTransitionResult,
  CandidateRelationshipEvent,
  SetWizardCompanionInput,
  UpdateCompanionDescriptionInput,
} from "./world-relationship-transitions";
export {
  applySetWizardHomeIsleV5Candidate,
  applySetWizardSanctumV5Candidate,
  applySetWizardCompanionV5Candidate,
  applyUpdateCompanionDescriptionV5Candidate,
} from "./world-relationship-transitions";

export type {
  HierophantFlameLawId,
  HierophantFlameLawDefinition,
  HierophantStartingTempleId,
  HierophantTempleId,
  HierophantTempleKind,
  HierophantStartingTempleDefinition,
  OrdinaryHierophantStartingTempleDefinition,
  HestarHierophantStartingTempleDefinition,
  HierophantBuiltinClassId,
  HierophantBuiltinClassDefinition,
  HierophantBuiltinDoctrineId,
  HierophantBuiltinBlasphemyId,
  HierophantBuiltinDoctrineDefinition,
  HierophantCampaignTempleId,
  HierophantDogmaCategory,
  HierophantBuiltinDogmaCategory,
  HierophantBuiltinDogmaId,
  HierophantBuiltinDogmaDefinition,
  HierophantLiturgicalHolidayId,
  HierophantLiturgicalObservance,
  HierophantLiturgicalHolidayDefinition,
  HierophantOrdinaryStartingTempleId,
} from "./hierophant-catalogs";
export {
  HIEROPHANT_FLAME_LAW_IDS,
  HIEROPHANT_FLAME_LAW_DEFINITIONS,
  hierophantFlameLawApplicationLabel,
  hierophantFlameLawDisplayName,
  hierophantFlameLawText,
  isValidHierophantFlameLawId,
  HIEROPHANT_BUILTIN_CLASS_IDS,
  HIEROPHANT_BUILTIN_CLASS_DEFINITIONS,
  isValidHierophantBuiltinClassId,
  HIEROPHANT_BUILTIN_DOCTRINE_IDS,
  HIEROPHANT_BUILTIN_BLASPHEMY_IDS,
  HIEROPHANT_BUILTIN_DOCTRINE_DEFINITIONS,
  isValidHierophantBuiltinDoctrineId,
  isValidHierophantBuiltinBlasphemyId,
  hierophantBuiltinDoctrineDefinition,
  HIEROPHANT_STARTING_TEMPLE_IDS,
  HIEROPHANT_STARTING_TEMPLE_DEFINITIONS,
  hierophantStartingTempleDisplayName,
  isValidHierophantStartingTempleId,
  isValidHierophantCampaignTempleId,
  isValidHierophantTempleId,
  isValidHierophantCampaignClassId,
  isValidHierophantCampaignDoctrineId,
  isValidHierophantCampaignBlasphemyId,
  isValidHierophantDogmaEntryId,
  hierophantStartingTempleDefinition,
  HIEROPHANT_DOGMA_CATEGORIES,
  isValidHierophantDogmaCategory,
  HIEROPHANT_BUILTIN_DOGMA_IDS,
  HIEROPHANT_BUILTIN_DOGMA_DEFINITIONS,
  isValidHierophantBuiltinDogmaId,
  HIEROPHANT_CLASS_ENJOYED_DOGMA_CATEGORIES,
  HIEROPHANT_LITURGICAL_HOLIDAY_IDS,
  HIEROPHANT_LITURGICAL_HOLIDAY_DEFINITIONS,
  isValidHierophantLiturgicalHolidayId,
  hierophantLiturgicalHolidayDefinition,
} from "./hierophant-catalogs";

export type {
  HierophantCampaignClassId,
  HierophantClassId,
  HierophantCampaignDoctrineId,
  HierophantDoctrineId,
  HierophantCampaignBlasphemyId,
  HierophantBlasphemyId,
  HierophantDogmaEntryId,
  HierophantTempleStatus,
  OrdinaryTempleDoctrineState,
  OrdinaryHierophantTemple,
  HestarHierophantTemple,
  HierophantTemple,
  HierophantCampaignClass,
  HierophantCampaignBlasphemy,
  HierophantCampaignDoctrine,
  HierophantTempleArea,
  HierophantSupplicantHost,
  HierophantSupplicant,
  HierophantProphetDisposition,
  HierophantProphetHost,
  HierophantProphet,
  HierophantCultDogma,
  HierophantCult,
  HierophantState,
} from "./hierophant-state";
export { EMPTY_HIEROPHANT_STATE } from "./hierophant-state";

export { validateHierophantStructure, validateHierophantReferenceIntegrity } from "./hierophant-validation";

export type {
  MarinerBoardIsleId,
  MarinerExternalLandId,
  MarinerHorizonCardinalGroupId,
  MarinerHorizonRegionId,
  MarinerInteriorSeaRegionId,
  MarinerSeaRegionId,
  MarinerLawOfSeaId,
  MarinerBuiltinBeastId,
  MarinerArrangementId,
  MarinerRouteEndpoint,
  MarinerRouteId,
  MarinerBoardIsleDefinition,
  MarinerExternalLandDefinition,
  MarinerRouteDefinition,
  MarinerInteriorSeaRegionDefinition,
  MarinerHorizonRegionDefinition,
  MarinerSeaRegionDefinition,
  MarinerHorizonCardinalGroupDefinition,
  MarinerLawOfSeaDefinition,
  MarinerBuiltinBeastDefinition,
  MarinerArrangementRaider,
  MarinerArrangementDefinition,
} from "./mariner-catalogs";
export {
  MARINER_BOARD_ISLE_IDS,
  MARINER_EXTERNAL_LAND_IDS,
  MARINER_HORIZON_CARDINAL_GROUP_IDS,
  MARINER_HORIZON_REGION_IDS,
  MARINER_INTERIOR_SEA_REGION_IDS,
  MARINER_SEA_REGION_IDS,
  MARINER_LAW_OF_SEA_IDS,
  MARINER_BUILTIN_BEAST_IDS,
  MARINER_ARRANGEMENT_IDS,
  MARINER_BOARD_ISLE_DEFINITIONS,
  MARINER_EXTERNAL_LAND_DEFINITIONS,
  MARINER_ROUTE_DEFINITIONS,
  MARINER_ROUTE_IDS,
  MARINER_HORIZON_CARDINAL_GROUPS,
  MARINER_SEA_REGION_DEFINITIONS,
  MARINER_LAW_OF_SEA_DEFINITIONS,
  MARINER_BUILTIN_BEAST_DEFINITIONS,
  MARINER_ARRANGEMENT_DEFINITIONS,
  marinerRouteId,
  marinerRouteDefinition,
  isValidMarinerBoardIsleId,
  isValidMarinerExternalLandId,
  isValidMarinerSeaRegionId,
  isValidMarinerHorizonRegionId,
  isValidMarinerLawOfSeaId,
  isValidMarinerBuiltinBeastId,
  isValidMarinerRouteId,
  marinerRouteEndpointsEqual,
  marinerRouteHasEndpoint,
  isValidMarinerArrangementId,
  marinerArrangementDefinition,
} from "./mariner-catalogs";

export type {
  MarinerIsleMarket,
  MarinerBoardIsleState,
  MarinerRouteOccupancy,
  MarinerRouteState,
  MarinerSeaRegionState,
  MarinerBeastCondition,
  MarinerBeastLocation,
  MarinerBeastState,
  MarinerState,
  InitializedDefaultMarinerInput,
} from "./mariner-state";
export {
  EMPTY_MARINER_STATE,
  buildInitializedDefaultMarinerState,
} from "./mariner-state";

export { validateMarinerStructure, validateMarinerReferenceIntegrity } from "./mariner-validation";

export type {
  NecromancerGateStatus,
  NecromancerGateBand,
  NecromancerPathRegion,
  NecromancerGhoulCallerDisposition,
  NecromancerAbominationKind,
  NecromancerLawVisibility,
  NecromancerBuiltinGateId,
  NecromancerCampaignGateId,
  NecromancerGateId,
  NecromancerEdgePathSpaceId,
  NecromancerFarLandsPathSpaceId,
  NecromancerAbyssPathSpaceId,
  NecromancerBuiltinPathSpaceId,
  NecromancerCampaignPathSpaceId,
  NecromancerPathSpaceId,
  NecromancerTerminalExitId,
  NecromancerLawOfDeathId,
  NecromancerArrangementId,
  NecromancerOccupiableSpaceRef,
  NecromancerTerminalTarget,
  NecromancerStaticTerminalExit,
  NecromancerDirectedStep,
  NecromancerBuiltinGateDefinition,
  NecromancerBuiltinPathSpaceDefinition,
  NecromancerTerminalExitDefinition,
  NecromancerLawOfDeathDefinition,
  NecromancerArrangementDefinition,
} from "./necromancer-catalogs";
export {
  NECROMANCER_GATE_STATUS_VALUES,
  NECROMANCER_GATE_BANDS,
  NECROMANCER_PATH_REGIONS,
  NECROMANCER_GHOUL_CALLER_DISPOSITIONS,
  NECROMANCER_ABOMINATION_KINDS,
  NECROMANCER_LAW_VISIBILITIES,
  NECROMANCER_BUILTIN_GATE_IDS,
  NECROMANCER_EDGE_PATH_SPACE_IDS,
  NECROMANCER_FAR_LANDS_PATH_SPACE_IDS,
  NECROMANCER_ABYSS_PATH_SPACE_IDS,
  NECROMANCER_BUILTIN_PATH_SPACE_IDS,
  NECROMANCER_TERMINAL_EXIT_IDS,
  NECROMANCER_LAW_OF_DEATH_IDS,
  NECROMANCER_ARRANGEMENT_IDS,
  NECROMANCER_BUILTIN_GATE_DEFINITIONS,
  NECROMANCER_BUILTIN_PATH_SPACE_DEFINITIONS,
  NECROMANCER_TERMINAL_EXIT_DEFINITIONS,
  NECROMANCER_LAW_OF_DEATH_DEFINITIONS,
  NECROMANCER_DEFAULT_INTERNAL_STEPS,
  NECROMANCER_DEFAULT_TERMINAL_EXITS,
  NECROMANCER_QUIET_ARRANGEMENT_SOUL_LOCATIONS,
  NECROMANCER_ARRANGEMENT_DEFINITIONS,
  isValidNecromancerBuiltinGateId,
  isValidNecromancerCampaignGateId,
  isValidNecromancerGateId,
  isValidNecromancerBuiltinPathSpaceId,
  isValidNecromancerCampaignPathSpaceId,
  isValidNecromancerPathSpaceId,
  isValidNecromancerTerminalExitId,
  isValidNecromancerLawOfDeathId,
  isValidNecromancerArrangementId,
  isValidNecromancerGateStatus,
  isValidNecromancerGateBand,
  isValidNecromancerPathRegion,
  isValidNecromancerGhoulCallerDisposition,
  isValidNecromancerAbominationKind,
  isValidNecromancerLawVisibility,
  isBuiltinEdgeOfLifePathSpaceId,
  necromancerBuiltinGateDefinition,
  necromancerBuiltinPathSpaceDefinition,
  necromancerArrangementDefinition,
  necromancerOccupiableSpaceRefsEqual,
  necromancerDirectedStepsEqual,
  necromancerDirectedStepKey,
  necromancerDefaultInternalOutgoingTarget,
} from "./necromancer-catalogs";

export type {
  NecromancerDepthState,
  NecromancerSelectedLaw,
  NecromancerBuiltinGateState,
  NecromancerCampaignGateState,
  NecromancerGateState,
  NecromancerBuiltinPathSpaceState,
  NecromancerCampaignPathSpaceState,
  NecromancerPathSpaceState,
  NecromancerSoulCount,
  NecromancerFoeLocation,
  NecromancerFoeState,
  NecromancerFoeSubjectRef,
  NecromancerDenizenFoeState,
  NecromancerWizardFoeState,
  NecromancerWizardTraversalKind,
  NecromancerWizardTraversalState,
  NecromancerAllyState,
  NecromancerGhoulCallerState,
  NecromancerState,
  InitializedDefaultNecromancerInput,
} from "./necromancer-state";
export {
  EMPTY_NECROMANCER_STATE,
  buildInitializedDefaultNecromancerState,
  necromancerFoeSubjectKey,
  necromancerFoeSubjectsEqual,
  isNecromancerWizardFoe,
  isNecromancerDenizenFoe,
  isValidNecromancerWizardTraversalKind,
  NECROMANCER_WIZARD_TRAVERSAL_KINDS,
} from "./necromancer-state";

export { validateNecromancerStructure, validateNecromancerReferenceIntegrity } from "./necromancer-validation";

export type {
  FaustianSuit,
  FaustianRank,
  FaustianCardId,
  FaustianCardDefinition,
  FaustianCardFacing,
  FaustianCommunityId,
  FaustianCommunityDefinition,
  FaustianDevilLawId,
  FaustianDevilLawDefinition,
  FaustianDevilFormId,
  FaustianDevilFormOccasion,
  FaustianDevilFormDefinition,
  FaustianOriginClaimId,
  FaustianOriginClaimStatus,
  FaustianOriginClaimDefinition,
  FaustianAntagonistGoal,
  FaustianAntagonistGoalDefinition,
  FaustianAntagonistMethodName,
  FaustianAntagonistChipCount,
  FaustianMalignance,
} from "./faustian-catalogs";
export {
  FAUSTIAN_SUITS,
  FAUSTIAN_RANKS,
  FAUSTIAN_CARD_IDS,
  FAUSTIAN_CARD_DEFINITIONS,
  faustianCardId,
  isValidFaustianCardId,
  isValidFaustianSuit,
  isValidFaustianRank,
  FAUSTIAN_CARD_FACINGS,
  isValidFaustianCardFacing,
  FAUSTIAN_COMMUNITY_IDS,
  FAUSTIAN_COMMUNITY_DEFINITIONS,
  isValidFaustianCommunityId,
  FAUSTIAN_DEVIL_LAW_IDS,
  FAUSTIAN_DEVIL_LAW_DEFINITIONS,
  isValidFaustianDevilLawId,
  FAUSTIAN_DEVIL_FORM_IDS,
  FAUSTIAN_DEVIL_FORM_OCCASIONS,
  FAUSTIAN_DEVIL_FORM_DEFINITIONS,
  isValidFaustianDevilFormId,
  isValidFaustianDevilFormOccasion,
  FAUSTIAN_ORIGIN_CLAIM_IDS,
  FAUSTIAN_ORIGIN_CLAIM_STATUSES,
  FAUSTIAN_ORIGIN_CLAIM_DEFINITIONS,
  isValidFaustianOriginClaimId,
  isValidFaustianOriginClaimStatus,
  FAUSTIAN_ANTAGONIST_GOALS,
  FAUSTIAN_ANTAGONIST_GOAL_DEFINITIONS,
  isValidFaustianAntagonistGoal,
  faustianAntagonistGoalSuit,
  FAUSTIAN_ANTAGONIST_METHOD_NAMES,
  isValidFaustianAntagonistMethodName,
  FAUSTIAN_ANTAGONIST_CHIP_COUNTS,
  isValidFaustianAntagonistChipCount,
  FAUSTIAN_MALIGNANCES,
  isValidFaustianMalignance,
} from "./faustian-catalogs";

export type {
  FaustianSchemePlacement,
  FaustianCommunityState,
  FaustianMachinationCard,
  FaustianEntrustedCard,
  FaustianAntagonistBeneathCard,
  FaustianPossessionRepresentation,
  FaustianPossessionCard,
  FaustianDomainPlacedCard,
  FaustianConspiracyState,
  FaustianAntagonistState,
  FaustianDemonOccupancy,
  FaustianDemonBinding,
  FaustianDemonCondition,
  FaustianDemonState,
  FaustianDomainSeizure,
  FaustianOriginClaimState,
  FaustianCustomOriginClaim,
  FaustianSelectedDevilForms,
  FaustianDevilObligation,
  FaustianPersistentFullHouseRank,
  FaustianPersistentMachinationEffect,
  FaustianState,
  InitializedDefaultFaustianInput,
} from "./faustian-state";
export {
  EMPTY_FAUSTIAN_STATE,
  EMPTY_SELECTED_DEVIL_FORMS,
  FAUSTIAN_DEMON_CONDITIONS,
  FAUSTIAN_PERSISTENT_FULL_HOUSE_RANKS,
  buildInitializedDefaultFaustianState,
  faustianDeckMissingSuits,
  devilWeeksOwedForMissingSuits,
  isFaustianDeckEmpty,
  isValidFaustianDemonCondition,
  isValidFaustianPersistentFullHouseRank,
} from "./faustian-state";

export { validateFaustianStructure, validateFaustianReferenceIntegrity } from "./faustian-validation";

export type {
  SageLawOfDreamingId,
  SageLawOfDreamingDefinition,
  SageDestinySuit,
  SageDestinyRank,
  SageDestinyDefinitionId,
  SageDestinyDefinition,
  SageDreamscapeSegmentId,
  SageDreamscapeSegmentDefinition,
  SageCycleId,
  SageCycleDefinition,
  SageOrdinaryFairyNameGlyph,
  SageDreamingCondition,
  SageFutureCondition,
  SageDestinyAssignmentStatus,
  SageFairyForm,
  SageDruidGrade,
} from "./sage-catalogs";
export {
  SAGE_LAW_OF_DREAMING_IDS,
  SAGE_LAW_OF_DREAMING_DEFINITIONS,
  isValidSageLawOfDreamingId,
  SAGE_DESTINY_SUITS,
  SAGE_DESTINY_RANKS,
  SAGE_DESTINY_DEFINITIONS,
  SAGE_DESTINY_DEFINITION_IDS,
  isValidSageDestinyDefinitionId,
  isValidSageDestinySuit,
  isValidSageDestinyRank,
  sageDestinyDefinition,
  SAGE_DREAMSCAPE_SEGMENT_IDS,
  SAGE_DREAMSCAPE_SEGMENT_DEFINITIONS,
  isValidSageDreamscapeSegmentId,
  SAGE_CYCLE_IDS,
  SAGE_CYCLE_DEFINITIONS,
  isValidSageCycleId,
  sageCycleDefinition,
  SAGE_ORDINARY_FAIRY_NAME_GLYPHS,
  isValidSageOrdinaryFairyNameGlyph,
  SAGE_DREAMING_CONDITIONS,
  isValidSageDreamingCondition,
  SAGE_FUTURE_CONDITIONS,
  isValidSageFutureCondition,
  SAGE_DESTINY_ASSIGNMENT_STATUSES,
  isValidSageDestinyAssignmentStatus,
  SAGE_FAIRY_FORMS,
  isValidSageFairyForm,
  SAGE_DRUID_GRADES,
  isValidSageDruidGrade,
} from "./sage-catalogs";

export type {
  SageDestinyInstanceId,
  SageDestinyInstance,
  SageAssignedDestiny,
  SageOmenLocation,
  SageOmenEntry,
  SageDreamscapeDenizenAssociation,
  SageOrdinaryFairyName,
  SageFairyTrueName,
  SageFairyName,
  SageFairyOverlay,
  SageDruidOverlay,
  SageLostDreamerState,
  SageState,
} from "./sage-state";
export {
  EMPTY_SAGE_STATE,
  isValidSageDestinyInstanceId,
  sageOmenLocationKey,
} from "./sage-state";

export { validateSageStructure, validateSageReferenceIntegrity } from "./sage-validation";

export type {
  WarlockSourceClanId,
  WarlockEmergentClanId,
  WarlockClanId,
  WarlockSourceHeraldry,
  WarlockClanKind,
  WarlockClanDefinition,
  WarlockIdeologyId,
  WarlockIdeologyDefinition,
  WarlockCourtLawId,
  WarlockCourtLawDefinition,
  WarlockLordTitleId,
  WarlockTitleBaseSetupPlacement,
  WarlockLordTitleDefinition,
  WarlockHeroicTitleGlyph,
  WarlockHeroFame,
  WarlockArmyLifecycle,
  WarlockCourtCondition,
  WarlockKingHealthCondition,
} from "./warlock-catalogs";
export {
  WARLOCK_SOURCE_CLAN_IDS,
  WARLOCK_EMERGENT_CLAN_IDS,
  WARLOCK_CLAN_IDS,
  WARLOCK_SOURCE_HERALDRY_VALUES,
  WARLOCK_SOURCE_CLAN_HERALDRY,
  WARLOCK_CLAN_DEFINITIONS,
  isValidWarlockClanId,
  isValidWarlockSourceClanId,
  WARLOCK_IDEOLOGY_IDS,
  WARLOCK_IDEOLOGY_DEFINITIONS,
  isValidWarlockIdeologyId,
  WARLOCK_COURT_LAW_IDS,
  WARLOCK_COURT_LAW_DEFINITIONS,
  isValidWarlockCourtLawId,
  WARLOCK_LORD_TITLE_IDS,
  WARLOCK_LORD_TITLE_DEFINITIONS,
  isValidWarlockLordTitleId,
  warlockLordTitleDefinition,
  WARLOCK_HEROIC_TITLE_GLYPHS,
  isValidWarlockHeroicTitleGlyph,
  WARLOCK_HERO_FAME_VALUES,
  isValidWarlockHeroFame,
  WARLOCK_ARMY_LIFECYCLE_VALUES,
  isValidWarlockArmyLifecycle,
  WARLOCK_COURT_CONDITIONS,
  isValidWarlockCourtCondition,
  WARLOCK_KING_HEALTH_CONDITIONS,
  isValidWarlockKingHealthCondition,
} from "./warlock-catalogs";

export type {
  WarlockCampaignCourtLawId,
  WarlockGarrisonId,
  WarlockRebellionId,
  WarlockRelocatedMarketId,
  WarlockClanState,
  WarlockCampaignCourtLaw,
  WarlockCourtLawRef,
  WarlockLordTitleState,
  WarlockClanDeckState,
  WarlockQuestTitleState,
  WarlockFaustianAccompliceTitleState,
  WarlockKingState,
  WarlockLadyOverlay,
  WarlockErrantHeraldry,
  WarlockErrantClaim,
  WarlockErrantLadyOverlay,
  WarlockAuthorityTarget,
  WarlockAuthorityEntry,
  WarlockGarrisonState,
  WarlockArmySponsor,
  WarlockArmyOverlay,
  WarlockHeroicTitle,
  WarlockHeroOverlay,
  WarlockRebellionState,
  WarlockClanHeraldryCount,
  WarlockMarketHeraldryState,
  WarlockRelocatedMarketState,
  WarlockPartnership,
  WarlockState,
} from "./warlock-state";
export {
  EMPTY_WARLOCK_STATE,
  isValidWarlockCampaignCourtLawId,
  isValidWarlockGarrisonId,
  isValidWarlockRebellionId,
  isValidWarlockRelocatedMarketId,
  warlockAuthorityTargetKey,
} from "./warlock-state";

export { validateWarlockStructure, validateWarlockReferenceIntegrity } from "./warlock-validation";

export type {
  SorcererSourceSchoolId,
  CampaignSchoolOfMagicId,
  SorcererSourceSchoolDefinition,
  SorcererLawOfMagicId,
  SorcererLawOfMagicDefinition,
  SorcererSourceReagentId,
  SorcererSourceReagentDefinition,
  SorcererBuiltinAlchemicalRecipeId,
  SorcererBuiltinAlchemicalRecipeDefinition,
  SorcererArrangementId,
} from "./sorcerer-catalogs";
export {
  SORCERER_SOURCE_SCHOOL_IDS,
  SORCERER_SOURCE_SCHOOL_DEFINITIONS,
  isValidSorcererSourceSchoolId,
  isValidCampaignSchoolOfMagicId,
  sorcererSourceSchoolDefinition,
  SORCERER_LAW_OF_MAGIC_IDS,
  SORCERER_LAW_OF_MAGIC_DEFINITIONS,
  isValidSorcererLawOfMagicId,
  sorcererLawOfMagicDefinition,
  SORCERER_SOURCE_REAGENT_IDS,
  SORCERER_SOURCE_REAGENT_DEFINITIONS,
  isValidSorcererSourceReagentId,
  sorcererSourceReagentDefinition,
  SORCERER_BUILTIN_ALCHEMICAL_RECIPE_IDS,
  SORCERER_BUILTIN_ALCHEMICAL_RECIPE_DEFINITIONS,
  isValidSorcererBuiltinAlchemicalRecipeId,
  sorcererBuiltinAlchemicalRecipeDefinition,
  SORCERER_ARRANGEMENT_IDS,
  isValidSorcererArrangementId,
} from "./sorcerer-catalogs";

export type {
  GrimoireSpellId,
  GrimoireSpellDefinition,
} from "./grimoire-catalog";
export {
  GRIMOIRE_SPELL_IDS,
  GRIMOIRE_SPELL_DEFINITIONS,
  GRIMOIRE_GREAT_WORK_SPELL_IDS,
  isValidGrimoireSpellId,
  grimoireSpellDefinition,
} from "./grimoire-catalog";

export type {
  MagicSchoolRef,
  MagicConsumableCustody,
  TomeStack,
  ReagentStack,
  MagicConsumablesState,
} from "./magic-consumables";
export {
  EMPTY_MAGIC_CONSUMABLES_STATE,
  magicSchoolRefKey,
  magicConsumableCustodyKey,
  tomeStackKey,
  reagentStackKey,
  validateMagicConsumablesStructure,
} from "./magic-consumables";

export type {
  SorcererResearchPositionId,
  SorcererBaseResearchPositionId,
  SorcererCampaignResearchPositionId,
  SorcererInnovationId,
  SorcererCampaignAcademicKindId,
  SorcererCampaignRecipeId,
  SorcererCampaignKnowledgeMethodId,
  SorcererResearchPositionTarget,
  SorcererResearchPosition,
  SorcererResearcher,
  SorcererRecipeRef,
  SorcererAcademicRole,
  SorcererAcademic,
  SorcererKnowledgeState,
  SorcererArcanistRank,
  SorcererDisruptiveArcanistProfile,
  SorcererArcanistPlacement,
  SorcererArcanist,
  SorcererConstructInstruction,
  SorcererConstructOverlay,
  SorcererInnovation,
  SorcererCampaignSchoolDefinition,
  SorcererCampaignAcademicKindDefinition,
  SorcererCampaignRecipeDefinition,
  SorcererCampaignKnowledgeMethodDefinition,
  SorcererState,
  SourceResearchPositionTopologyInput,
} from "./sorcerer-state";
export {
  SORCERER_BASE_RESEARCH_POSITION_IDS,
  SORCERER_RESEARCH_TEMPLE_IDS,
  SORCERER_ORRERY_RESEARCH_POSITION_IDS,
  SORCERER_TEMPLE_RESEARCH_POSITION_IDS,
  SORCERER_ARCANIST_RANKS,
  EMPTY_SORCERER_KNOWLEDGE_STATE,
  EMPTY_SORCERER_STATE,
  isValidSorcererBaseResearchPositionId,
  isValidSorcererCampaignResearchPositionId,
  isValidSorcererResearchPositionId,
  isValidSorcererInnovationId,
  isValidSorcererCampaignAcademicKindId,
  isValidSorcererCampaignRecipeId,
  isValidSorcererCampaignKnowledgeMethodId,
  isValidSorcererArcanistRank,
  isOrreryResearchPositionId,
  buildSourceResearchPositions,
} from "./sorcerer-state";

export { validateSorcererStructure, validateSorcererReferenceIntegrity, validateMagicConsumablesReferenceIntegrity, isExactEmptySorcerer } from "./sorcerer-validation";

export type {
  SorcererTransitionResult,
  SorcererResearcherAssignment,
  SorcererTowerArcanistIntent,
  SorcererLibrarianIntent,
  SorcererCalamityDisruptiveArcanistIntent,
  InitializeSorcererInput,
} from "./sorcerer-transitions";
export {
  canonicalizeInitializeSorcererInput,
  applyInitializeSorcerer,
} from "./sorcerer-transitions";

export type { FaustianTransitionResult } from "./faustian-transitions";
export {
  applyInvestigateFaustianCommunity,
  applyBlackmailFaustianCommunity,
  applyDirectFaustianAccomplice,
  applyDisruptFaustianPawn,
} from "./faustian-transitions";

export type {
  NecromancerTransitionResult,
  NecromancerArrangementFoeBinding,
  NecromancerArrangementAllyBinding,
  NecromancerArrangementGhoulCallerBinding,
  InitializeNecromancerInput,
  CreateNecromancerCampaignGateInput,
  UpdateNecromancerCampaignGateFields,
  CreateNecromancerCampaignPathSpaceInput,
  UpdateNecromancerFoeFields,
  UpdateNecromancerWizardTraversalFields,
  AddNecromancerWizardFoeTruthInput,
  UpdateNecromancerAllyFields,
  UpdateNecromancerGhoulCallerFields,
} from "./necromancer-transitions";
export {
  canonicalizeNecromancerCampaignGateName,
  canonicalizeCreateNecromancerCampaignGateInput,
  canonicalizeUpdateNecromancerCampaignGateFields,
  canonicalizeNecromancerGhoulCallerProfileText,
  canonicalizeNecromancerArrangementGhoulCallerBinding,
  canonicalizeInitializeNecromancerInput,
  canonicalizeNecromancerGhoulCaller,
  canonicalizeUpdateNecromancerGhoulCallerFields,
  applyInitializeNecromancer,
  applySetNecromancerDepth,
  applySetNecromancerSelectedLaws,
  applySetNecromancerGateStatus,
  applySetNecromancerSoulCount,
  applyMoveNecromancerSouls,
  applyAddNecromancerFoe,
  applyUpdateNecromancerFoe,
  applyRemoveNecromancerFoe,
  applyEscapeNecromancerWizardFoe,
  applyAddNecromancerWizardFoeTruth,
  applyUpdateNecromancerWizardFoeTruth,
  applyRemoveNecromancerWizardFoeTruth,
  applyAddNecromancerWizardTraversal,
  applyUpdateNecromancerWizardTraversal,
  applyRemoveNecromancerWizardTraversal,
  applyAddNecromancerAlly,
  applyUpdateNecromancerAlly,
  applyRemoveNecromancerAlly,
  applyAddNecromancerGhoulCaller,
  applyUpdateNecromancerGhoulCaller,
  applyRemoveNecromancerGhoulCaller,
  applyCreateNecromancerCampaignGate,
  applyUpdateNecromancerCampaignGate,
  applyCreateNecromancerCampaignPathSpace,
  applyRemoveNecromancerCampaignPathSpace,
  applyAddNecromancerStep,
  applyRemoveNecromancerStep,
} from "./necromancer-transitions";

export type {
  MarinerTransitionResult,
  MarinerIsleBinding,
  MarinerRarityDescription,
  InitializeMarinerInput,
  UpdateMarinerBeastFields,
} from "./mariner-transitions";
export {
  canonicalizeInitializeMarinerInput,
  normalizeMarinerIsleMarket,
  applyInitializeMariner,
  applySetMarinerShip,
  applySetSelectedSeaLaws,
  applySetMarinerRouteOccupancy,
  applySetMarinerSeaStormCount,
  applySetMarinerIsleMarket,
  applySetMarinerIsleRavage,
  applyAddMarinerBeast,
  applyUpdateMarinerBeast,
  applyRemoveMarinerBeast,
} from "./mariner-transitions";

export type {
  HierophantTransitionResult,
  TemplePlaceBinding,
  InitializeHierophantInput,
  AdjustTempleResourcesFields,
  CreateTempleInput,
  UpdateTempleFields,
  UpdateSupplicantFields,
  UpdateProphetFields,
  UpdateCultFields,
  UpdateCultDogmaFields,
  UpdateCampaignDoctrineFields,
} from "./hierophant-transitions";
export {
  applyInitializeHierophant,
  applyAdjustTempleResources,
  applyCreateTemple,
  applyUpdateTemple,
  applySetTempleHoliday,
  applySetSelectedFlameLaws,
  applyAddSupplicant,
  applyUpdateSupplicant,
  applyRemoveSupplicant,
  applyAddProphet,
  applyUpdateProphet,
  applyRemoveProphet,
  applyEstablishCult,
  applyUpdateCult,
  applyRemoveCult,
  applyAddCultDogma,
  applyUpdateCultDogma,
  applyRemoveCultDogma,
  applyCreateCampaignClass,
  applyUpdateCampaignClass,
  applyCreateCampaignDoctrine,
  applyUpdateCampaignDoctrine,
} from "./hierophant-transitions";

// --- V5 Integration Transitions (candidate, not active) ---

export type {
  WizardCharacterPatchV5,
  V5IntegrationTransitionResult,
  SetEngagementTargetV5Input,
  RescheduleEngagementV5Input,
} from "./v5-integration-transitions";
export {
  normalizeWizardCharacterPatchV5,
  validateEngagementTargetV5,
  applyUpdateWizardCharacterV5Candidate,
  applySetEngagementTargetV5Candidate,
  applyRescheduleEngagementV5Candidate,
} from "./v5-integration-transitions";

export type {
  SourceLoreCollectionId,
  SourceLoreTopicId,
  SourceLoreEntryId,
  LoreSubjectKind,
  SourceLoreBindingDescriptor,
  SourceLoreAttribution,
  SourceLoreEntryDefinition,
  SourceLoreCollectionDefinition,
  SourceLoreCatalog,
  SourceLoreCatalogLookup,
  SourceLorePreviewResult,
} from "./lore-catalog";
export {
  LORE_SUBJECT_KINDS,
  DRAFT4_V1_SOURCE_LORE_COLLECTIONS,
  DRAFT4_V1_SOURCE_LORE_CATALOG,
  DRAFT4_V1_SOURCE_LORE_COLLECTION_IDS,
  DRAFT4_V1_SOURCE_LORE_TOPIC_IDS,
  DRAFT4_V1_SOURCE_LORE_CATALOG_SEMANTIC_DIGEST,
  isValidSourceLoreCollectionId,
  isValidSourceLoreTopicId,
  isValidSourceLoreEntryIdFormat,
  isValidLoreSubjectKind,
  lookupSourceLoreCatalog,
  sourceLoreCollectionDefinition,
  sourceLoreEntryIds,
  sourceLoreCatalogCoverage,
  sourceLoreCatalogSemanticManifest,
  previewSourceLoreCollection,
} from "./lore-catalog";

export type {
  LoreSubjectRef,
  SourceLoreEntryOverride,
  CampaignAuthoredLoreEntry,
  InstantiatedSourceLoreCollection,
  CampaignLoreCollection,
  LoreState,
  EffectiveLoreEntry,
  LoreBindingResolution,
  MarinerIsleLoreContextSelection,
  MarinerDelegatedIsleOwnerSeatId,
  EffectiveSourceLoreRead,
} from "./lore-state";
export {
  EMPTY_LORE_STATE,
  MARINER_DELEGATED_ISLE_OWNER_SEATS,
  MARINER_ISLE_LORE_DELEGATION,
  MARINER_FAR_REACH_SOURCE_COLLECTION_ID,
  loreSubjectKey,
  loreSubjectRefsEqual,
  instantiatedSourceLoreCollection,
  campaignLoreCollectionForSubject,
  composeEffectiveSourceLore,
  readEffectiveSourceLore,
  readEffectiveSourceLoreForRuleset,
  readCampaignLoreCollectionEntries,
  resolveSourceLoreBinding,
  selectMarinerIsleLoreContext,
  selectedMarinerIsleLoreAvailability,
  catalogForCampaignRuleset,
  expectedSubjectKindForBinding,
} from "./lore-state";

export { validateLoreStructure, validateLoreReferenceIntegrity, assertValidStoredLoreText, validateLoreSubjectRef, MAX_LORE_TEXT_LENGTH } from "./lore-validation";

export type {
  AddLoreEntryTarget,
  AddLoreEntryInput,
  ReviseLoreEntryTarget,
  ReviseLoreEntryInput,
  LoreTransitionResult,
} from "./lore-transitions";
export {
  applyAddLoreEntry,
  applyReviseLoreEntry,
} from "./lore-transitions";
